### ISSUE TITLE
[Feedback] Conan essentials: Exercise 9a : Upload to Artifactory: failed 400 V2 layout

### ISSUE THREAD

**Issue by NeroBurner** [conan-io/training#40]
https://academy.jfrog.com/path/conan/conan-essentials/583137

The command `conan upload "hello*" -r artifactory` fails

```sh
$ conan upload "hello*" -r artifactory
Are you sure you want to upload 'hello/0.1@user/testing' to 'artifactory'? (yes/no): yes
Uploading to remote 'artifactory':
Uploading hello/0.1@user/testing to remote 'artifactory'                                 
Compressing conan_sources.tgz completed [3 files]                                        
Please log in to "artifactory" to perform this action. Execute "conan user" command.
Remote 'artifactory' username: user@email.com
Please enter a password for "user@email.com" account: 
ERROR: hello/0.1@user/testing: Upload recipe to 'artifactory' failed: 400: Conan is not yet migrated to V2 layout. Check logs for progress details.. [Remote: artifactory]

ERROR: Errors uploading some packages
```

Conan version is `1.30.0`

**Comment by memsharded** [comment]
Hi @NeroBurner 

Thanks for reporting. Quick question: Which Artifactory server are you using?

**Comment by NeroBurner** [comment]
https://neroburner23.jfrog.io

aws free tier created with https://jfrog.com/artifactory/start-free/

**Comment by memsharded** [comment]
I would like to make sure you are using the right path defined by SetMeUp.
Could you please post here the result of running ``conan remote list``?

**Comment by NeroBurner** [comment]
Sure :+1: 

```sh
$ conan remote list                                                               
conan-center: https://conan.bintray.com [Verify SSL: True]                                                     
artifactory: https://neroburner23.jfrog.io/artifactory/api/conan/myconanrepo [Verify SSL: True]
```

**Comment by memsharded** [comment]
Ok, it seems there is something wrong with the Artifactory free service, I am checking.

**Comment by memsharded** [comment]
https://status.jfrog.io/

**Comment by memsharded** [comment]
If you want to progress now, I would recommend downloading the .zip ArtifactoryCE from https://conan.io/downloads.html, unzipping, launching locally (app/bin/artifactory.bat). I usually do that and takes just a few minutes and works quite smoothly. Let me know if you need help with that.

**Comment by NeroBurner** [comment]
I tried the docker-one-liner from the downloads link. It is missing a space

```diff
- docker run --name artifactory -d -p 8081:8081 -p 8082:8082docker.bintray.io/jfrog/artifactory-cpp-ce:latest
+ docker run --name artifactory -d -p 8081:8081 -p 8082:8082 docker.bintray.io/jfrog/artifactory-cpp-ce:latest
```

needed to start the docker-artifactory two times, the first time I wrongly used `localhost` as my URL to access the artifactory, but the training is inside a docker container, so those two are different `localhost`s

On the second try I used `https://<my-local-ip>:8082` for artifactory URL and the upload now worked, thanks

**Comment by memsharded** [comment]
Cool, thanks for reporting, I will fix the command line now.

Lets keep this issue open until the problem with GoogleCloud (the thing that seems to be impacting Artifactory on the Cloud) is mitigated.

**Comment by memsharded** [comment]
Hi @NeroBurner 

It seems things have stabilized, at least from my side, my free tier instance is working fine. If you can, please give it another try and let me know if now it works. Thanks!


PS: The website has been fixed https://github.com/conan-io/website/commit/b000a8435b59a14a1a116ce1e16a6ab2a9db7930

**Comment by NeroBurner** [comment]
I just tried and I still get upload failed

```sh
conan remote update artifactory https://neroburner23.jfrog.io/artifactory/api/conan/myconanrepo

conan upload "hello*" -r=artifactory
Are you sure you want to upload 'hello/0.1@user/testing' to 'artifactory'? (yes/no): yes
Uploading to remote 'artifactory':
Uploading hello/0.1@user/testing to remote 'artifactory'                                 
Please log in to "artifactory" to perform this action. Execute "conan user" command.
Please enter a password for "user@email.com" account: 
ERROR: hello/0.1@user/testing: Upload recipe to 'artifactory' failed: 400: Conan is not yet migrated to V2 layout. Check logs for progress details.. [Remote: artifactory]

ERROR: Errors uploading some packages

**Comment by memsharded** [comment]
This is really weird. I am not sure what to check next, it seems that something is wrong with your server. If you are not using your instance for anything else rather than the training, you might share with me login credentials (you can also create a temporary user to remove later) to info@conan.io, and I can try to have a look and investigate a bit more.

**Comment by NeroBurner** [comment]
Yes, the cloud instance is just for the tutorial. Created a user `james` for you. Thank you for investigating

**Comment by memsharded** [comment]
Thanks for the access. I have been able to reproduce and it seems a glitch in the creation of recent Artifactory Free Tier instances. Older instances were working fine, but this new one is not providing full support for Conan at activation. 
We are investigating this, in the meantime we will recommend using a downloaded ArtifactoryCE instance instead.

Thanks very much for reporting and all the feedback and help!

**Comment by Vectrom** [comment]
Hello, I have the same problem on my new free instance (vectrom.jfrog.io). When we can expect a fix for it?

**Comment by memsharded** [comment]
Hi @Vectrom 

There is already a fix for it, for this training:

The docker-compose has been updated, now it includes a local ArtifactoryCE instance, so you can do the whole training without the FreeTier instance. If you have already cloned the training repo, do the following:

- Stop your current docker-compose: ``docker-compose down``
- Maybe not necessary, but I would do a cleanup of docker containers
- ``git pull``
- ``docker-compose up -d`` again
- The artifactory should be visible in localhost:8082. The docker Conan client will have visibility to it with a ``conan-training`` URL, it will be in the SetMeUp.

Please try that and let us know.

**Comment by NeroBurner** [comment]
@memsharded the bundled artifactory-training instance won't start for me. probably because of strict corporate proxy (I can pull containers, but the containers itself have no connectivity)

```sh
$ docker-compose logs artifactory-training | grep "\[ERROR\]"
artifactory-training    | 2020-10-12T06:34:01.261Z [jfrt ] [ERROR] [b41cf493e3dd3f2f] [ctoryContextConfigListener:116] [art-init            ] - Application could not be initialized: Found active HA servers in DB, Community Edition for C/C++ is not supported in by active HA environment. Shutting down Artifactory.
artifactory-training    | 2020-10-12T06:36:46.303Z [jffe ] [ERROR] [                ] [                              ] [main                ] - Error: Error starting application Failed pinging artifactory for 180Request failed with status code 404
```

**Comment by memsharded** [comment]
Hi @NeroBurner,

Thanks for reporting. I am not sure how a proxy would affect this, as everything is local in the docker. Also the message ``Community Edition for C/C++ is not supported in by active HA environment.`` makes no sense to me, as this is clearly not an HA environment. I'll ask @solvingj and @uilianries to investigate.

If in the meantime do you want to check if a "native" ArtifactoryCE works for you (just downloading, unzipping and executing the .bat or .sh inside app/bin), that could also provide more information to troubleshoot this issue.

**Comment by solvingj** [comment]
@NeroBurner Have you used docker before on this machine? If so, has the networking in other containers worked normally?

For `docker-compose up` to succeed for the first time, the developer container would need to successfully do  `apt-get` commands, which makes it seem like that container must at least have working internet. 

Indeed the error message about HA is very strange. We'll need to do some research on that error.

**Comment by NeroBurner** [comment]
I modified `conan-training` to use our `ribase` image, which is a `ubuntu` image plus the apt-proxy setup to work within our network. In the following the diff, which would work with the `ubuntu:focal` upstream image (locally I'm using our internal image):

```diff
----------------- docker_environment/conan-training/Dockerfile -----------------
index 6504db8..ebaa649 100644
@@ -1,19 +1,24 @@
-FROM conanio/gcc7:1.28.1
+FROM ubuntu:focal
 
 USER root
 
 RUN apt-get -qq update \
     && apt-get -qq install -y --no-install-recommends \
+       python3-pip \
        vim \
        nano \
        less \
+       g++ \
        g++-arm-linux-gnueabihf \
        cmake
+RUN pip3 install conan
+RUN useradd -ms /bin/bash conan
 
 USER conan
+WORKDIR /home/conan
 
 RUN git clone https://github.com/conan-io/training
 RUN conan profile new default --detect
 RUN conan profile update settings.compiler.libcxx=libstdc++11 default
 
 WORKDIR /home/conan/training
```

for the artifactory container I previously (successfully) used the `docker` command as mentioned in an earlier post

```sh
docker run --name artifactory -d -p 8081:8081 -p 8082:8082 docker.bintray.io/jfrog/artifactory-cpp-ce:latest
```

That container is stopped (not running), which I've checked with the `docker ps` command

**Comment by solvingj** [comment]
Ok, I"m confused about when you did these things and what the current state of your environment is.  This also seems to be an environment-specific challenge (until proven otherwise).  Is it possible we can continue chat in CPPLang Slack? I think it will take many questions and answers to help troubleshoot something like this.

**Comment by solvingj** [comment]
@NeroBurner please test the update in the PR provided and let us know if it fixes for you. It's easy to apply change manually if you need to.

**Comment by NeroBurner** [comment]
works perfectly with the new local `jfrog-artifactory-training` container, thanks a lot!

**Comment by memsharded** [comment]
> works perfectly with the new local jfrog-artifactory-training container, thanks a lot!

Thanks to you @NeroBurner for all the feedback and support!

**Comment by crazyawesome** [comment]
Hello @memsharded 
I also see the same error uploading to my free tier instance apai.jfrog.io. Since this ticket has been closed, does it mean the issue has been resolved (and hence, I am missing something in my setup) or is the solution to use the docker container instead? 

The docker container solution doesn't work so well for me because I am using a Linux virtual machine (command line only) on a Windows host, and forwarding the ports from the virtual machine to host machine etc. would add an additional layer of complexity for my demo/training to my colleagues. 

Nonetheless, I did try the docker container approach on my personal laptop (also on a Linux virtual machine, but now with a complete graphical user interface) and I only got as far as the "Artifactory is getting ready to work" animation followed by "Artifactory failed to initialize. Check the artifactory logs." (I don't remember the exact text of the error message.) I didn't know where the logs were so I couldn't make any progress there.

**Comment by memsharded** [comment]
Hi @crazyawesome 

It has been closed because the training now implements a **local Artifactory CE** instance, but yes, the FreeTier instances are still not working. Maybe we want to keep this issue open @solvingj while the FreeTier is not working?

> The docker container solution doesn't work so well for me because I am using a Linux virtual machine (command line only) on a Windows host, and forwarding the ports from the virtual machine to host machine etc. (as well as the need to install/explain docker) would add an additional layer of complexity for my demo/training to my colleagues. 

Some of the issues that have already been fixed is about some users running in a VM. As the Artifactory is hosted inside the same VM, it seems to work ok.

> Long story short, I would prefer to use the cloud-hosted artifactory in my demo/training and avoid the docker container approach, if it is possible.

Yes, we are on it, as soon as the Free Tier for Conan is working ok, we will report it.


In the meantime, then I would try the following:

- Download, unzip and run a native ArtifactoryCE, in your host environment. The .zip file works well, just unzip and double click on app/bin/artifactory.bat
- Make sure it connects in the browser in your host. Use the host IP, not localhost.
- Use only the Conan client from the docker-compose (you might even remove the Artifactory one).

I have tried this, and as the docker has visibility over the host IP, I managed to make it work. Please, let me know if this works for you.

**Comment by crazyawesome** [comment]
Thanks for taking the time to respond to my issue. 

>     * Download, unzip and run a native ArtifactoryCE, in your host environment. The .zip file works well, just unzip and double click on app/bin/artifactory.bat

I did initially start with this, but ran into the following error:

```
2020-10-18T06:54:10.474Z [1;33m[jfac ][0;39m [31m[WARN ][0;39m [a141dbb4e48023a1] [o.j.c.ExecutionUtils:142      ] [pool-18-thread-2    ] - Retry 550 Elapsed 4.98 minutes failed: Registration with router on URL http://localhost:8046 failed with error: UNAVAILABLE: io exception. Trying again
```

Then I decided to try using the docker container as below (in admin mode) and got another error:

```
C:\WINDOWS\system32>docker run --name artifactory -d -p 8081:8081 -p 8082:8082 docker.bintray.io/jfrog/artifactory-cpp-ce:latest
docker: Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.
See 'docker run --help'.
```

That's how I decided to host the artifactory on the cloud for the demo. 

I did look up for the above errors on stackoverflow and github, and tried many of the solutions suggested, but none seems to work. If I can figure out how to resolve either of the above errors, I can make do with it for now until the free tier issue is resolved. 

Some more background: The demo/training I mentioned above is also a "sales pitch". As mentioned in your [webinar](https://www.youtube.com/watch?v=xBLjXdyh3zs), various teams have their own "readme" files or "automation" scripts for the build process. I plan to propose the teams to adopt conan. I have 30 minutes for the explanation, demo and Q&A. Hence, the demo being error-free and simple would be beneficial. The complex stuff can be introduced later after people are convinced to use it. 😄

Also I realize this is not relevant to the problem, but for what it is worth, I use a different prototype project for this demo, found here: https://bitbucket.org/uchiha-madara/conan-gtest/src/master/

**Comment by memsharded** [comment]
> 020-10-18T06:54:10.474Z �[1;33m[jfac ]�[0;39m �[31m[WARN ]�[0;39m [a141dbb4e48023a1] [o.j.c.ExecutionUtils:142      ] [pool-18-thread-2    ] - Retry 550 Elapsed 4.98 minutes failed: Registration with router on URL http://localhost:8046 failed with error: UNAVAILABLE: io exception. Trying again

This is indeed weird, it could be something in your system (security tools, firewalls?) that is interfering with this launch, maybe @solvingj has more insights.

> Some more background: The demo/training I mentioned above is also a "sales pitch". As mentioned in your webinar, various teams have their own "readme" files or "automation" scripts for the build process. I plan to propose the teams to adopt conan. I have 30 minutes for the explanation, demo and Q&A. Hence, the demo being error-free and simple would be beneficial. The complex stuff can be introduced later after people are convinced to use it.

Yeah, totally, this is why we went first with the FreeTier. But this is also a brand new free service from JFrog, and we can understand that this failed. Hopefully this is fixed soon, and we can go back to it.

**Comment by solvingj** [comment]
@crazyawesome As @memsharded indicated, we'd really like to help you work through these issues and get a working training environment online.  Would you be able to continue troubleshooting via email or slack?

**Comment by solvingj** [comment]
Unfortunately, no environment will be free from caveats and/or variables which constitute challenges or even blockers for some users.  Our goal was to try to find a strategy which minimizes the number of such users, while still being testable and supportable with minimal resources locally.  In terms of providing a safe, repeatable and supportable environment for the exercises in the courses, we feel that the docker-compose approach is the best strategy available today.  We will continue to consider and seek out ways to improve what we have, so we welcome further feedback.  However, at this time, we will focus only on supporting the use of the current docker-based environment, featuring both the container for the local client commands, and the container for the local Artifactory server.

**Comment by crazyawesome** [comment]
> @crazyawesome As @memsharded indicated, we'd really like to help you work through these issues and get a working training environment online. Would you be able to continue troubleshooting via email or slack?

Thanks @solvingj. Yes certainly, I would like to continue troubleshooting this setup. How can I reach you over Slack?

**Comment by solvingj** [comment]
Great!
The slack workspace URL is here: https://cpplang.slack.com/

To get a new user invitation, you can use this link: https://cpplang-inviter.cppalliance.org/

Once joined, you can come to the #conan channel or message me directly @solvingj
